### ISSUE TITLE
a language other than English

### ISSUE THREAD

**Issue by hdw1472** [jordanmchavez/kdm-tts#6]
If you use a language other than English for a survivor name or annotation (eg Korean) and then save and load it, the language will be broken. can i know how to solve it??

**Comment by jordanmchavez** [comment]
I actually have no idea how TTS handles localization. It may have to do with how they save their files, *or* with how they display text. To determine which one it is, I'd try this: name your survivor with a Korean name, then save your game. Go in your save game folder (C:\Users\<your name>\Documents\My Games\Tabletop Simulator\Saves), then open up the .json file for your save (it will probably be the most recently changed one). Open it as a text file. Search for your survivor's name. If you find it, then it means TTS is saving the name properly, but displaying it improperly. If you don't find it, then it means TTS isn't saving it correctly. Regardless of which, I'd report this bug on the official TTS forums, since there's not much the mod can do to fix it.
